name:                treexercise
version:             0.1.0.0
github:              "githubuser/treexercise"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/treexercise#readme>

dependencies:
- base >= 4.7 && < 5
- generic-arbitrary

ghc-options:
- -freverse-errors
- -Wall
- -Werror
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monoid-instances
- -Wpartial-fields
- -Wsemigroup
- -Wno-unticked-promoted-constructors

default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveGeneric
- DeriveLift
- DeriveTraversable  # Implies: DeriveFoldable, DeriveFunctor
- DerivingVia  # Implies: DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances  # Implies: TypeSynonymInstances
- FunctionalDependencies  # Implies: MultiParamTypeClasses
- GADTs  # Implies: GADTSyntax, MonoLocalBinds
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MagicHash
- MultiParamTypeClasses  # Implies: ConstrainedClassMethods
- NamedFieldPuns
- NoMonomorphismRestriction
- NoStarIsType
- NoImplicitPrelude
- NumericUnderscores
- OverloadedStrings
- PatternSynonyms
- QuasiQuotes
- RankNTypes  # Implies: ExplicitForAll
- RecordWildCards  # Implies: DisambiguateRecordFields
- ScopedTypeVariables  # Implies: ExplicitForAll
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilyDependencies  # Implies: TypeFamilies
- TypeInType  # Implies: DataKinds, KindSignatures, PolyKinds
- TypeOperators  # Implies: ExplicitNamespaces
- ViewPatterns

library:
  source-dirs: src

executables:
  treexercise-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - treexercise

tests:
  treexercise-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - treexercise
    - hspec
    - QuickCheck
